### ISSUE TITLE
Host check

### ISSUE THREAD

**Issue by michel-cf** [Eyepea/tanto#8]
Although the services get checked, the host will always be marked as pending in Shinken/Nagios/Icinga.

I would propose that we do an optional host available update with every run.
As Tanto will usually be used to check the local system, testing if it is down is not really possible.
This does also mean that a host will never be marked as "down", but the same is true for the services. If the server itself is down, it won't send a service down notification.

I'm not aware if there is a way of generating an alert in Shinken(or Nagios/Icinga) if there has been no update for a passive host/service for x time.

**Comment by ludovic-gasc** [comment]
You need to play with options of Shinken/Nagios/Icinga for that: You can request an active check like ping and use passive checks for the rest.

I close this issue because it isn't Tanto related but Shinken/Nagios/Icinga configuration related, you can ask on their mailing lists for the support.
